---
apiVersion: v1
kind: Pod
metadata:
   name: time
   labels:
      app: time
spec:
   volumes:
   - name: time-cm-vol
     configMap:
        name: time
   containers:
   - name: time
     image: chukmunnlee/secure-node:v1
     imagePullPolicy: Always
     ports:
     - containerPort: 3000
   - name: time-opa
     image: openpolicyagent/opa:0.33.0-dev-static
     imagePullPolicy: IfNotPresent
     args: [ "run", "-s", "-b", "/app/bundle.tar.gz", "--addr", ":8181"]
     ports:
     - containerPort: 8181
     volumeMounts:
     - name: time-cm-vol
       mountPath: /app
